### ISSUE TITLE
Recipe for plot

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SimpleSDMLayers.jl#2]
Tagging @mkborregaard 

I added support for plots in this comment: https://github.com/EcoJulia/SimpleSDMLayers.jl/commit/41c4b6bf01a9a70938c810edb976560a31f70767

So far, this works with `density` and `histogram` (show the values) and `heatmap` (show the map). I am not sure how to proceed to make it work so that `plot` defaults to a heatmap - any tips?

**Comment by mkborregaard** [comment]
Sorry, I've been offline for a month and am travelling until mid-Sept. I commented on the commit.

**Comment by tpoisot** [comment]
:+1:
