### ISSUE TITLE
Sliding window analysis

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SimpleSDMLayers.jl#22]
As an alternative to `coarsen`, it could be really good to implement a sliding window approach, which can be either using blocks, or using all pixels below a certain Haversine distance.

**Comment by mkborregaard** [comment]
It doesn't look like they were involved, but just FYI there are good lightweight window functions in https://github.com/JeffreySarnoff/RollingFunctions.jl and little heavier but more powerful in https://github.com/JuliaImages/ImageFiltering.jl

**Comment by tpoisot** [comment]
Might be good to evaluate these in a future PR!

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
