### ISSUE TITLE
Integrate DataFrames.jl

### ISSUE THREAD

**Issue by gabrieldansereau** [EcoJulia/SimpleSDMLayers.jl#28]
It would be nice to have some built-in support for `DataFrames`, a bit like the `clip()` function for `GBIF` occurrences and possibly a `convert()` method to easily switch between layers and DataFrames. I'm thinking of some kind of optional dependency, like for GBIF (if possible, not sure if it can easily be done). I have some code I'll try to port here as soon as I can.

**Comment by tpoisot** [comment]
You can use the Require package to add additional functions when a package is loaded. Rather than convert, we can also declare new methods for DataFrame, SimpleSDMResponse, and SimpleSDMPredictor
