### ISSUE TITLE
SimpleSDMDataSources

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SimpleSDMLayers.jl#32]
All of this discussion about CHELSA in #31, as well as the amount of data managing code I had to write for #21, makes me wonder if we would not be better off with a `SimpleSDMDataSources.jl` package. In term, I'd like to offer access to more than bioclim on the CHELSA side, and maybe other earthenv layers as well. 

@gabrieldansereau and @mkborregaard what are your opinion on that? I don't think this tentative new package would be used on its own, but would instead be a way to separate the data download from the layer manipulation code.

**Comment by gabrieldansereau** [comment]
I'd favour keeping everything in a single package, if possible, especially if the two packages would not be used separately. I feel it's simpler and less confusing to have everything in one place. As an outsider, I find it confusing when features for a package are scattered across multiple repositories. 

I also think it's easier to publicize this way, like "hey here's a package that lets you access _and_ manipulate SDM data easily".

On the other hand, I'm all for offering access to more data, and I haven't tried implementing it. If you feel that having two packages would make it easier to implement and maintain, then I'm fine with it.

**Comment by tpoisot** [comment]
Good point about usability - my idea was that the functions would be accessible from `SimpleSDMLayers` in a transparent way, _but_ the functions themselves would be separated. This would help separate the testing issues since a lot of problems (including timeouts) are because of the data download.

`SimpleSDMDataSources` would be a dependency of `SimpleSDMLayers`, for sure, and users wouldn't need to interact with it directly.

**Comment by tpoisot** [comment]
Here is an overview of the proposed package: https://github.com/EcoJulia/SimpleSDMLayers.jl

This should be relatively easy to integrate to this one?
