### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SimpleSDMLayers.jl#4]
@mkborregaard I've solved the issues related to GDAL updates, and to `curl` doing weird things on some machines (by using HTTP instead) -- I think this is usable for light explorations (@gabrieldansereau is using it at the moment), what is your opinion on a `v0.0.1` version?

**Comment by tpoisot** [comment]
Of course I'd need to write some of the missing docstrings... Looking forward to it :upside_down_face:

**Comment by mkborregaard** [comment]
Yes! definitely ready for .0.0.1. Also this is a really great package, based on playing with it a bit.

**Comment by mkborregaard** [comment]
Do you need me to do something other here?

**Comment by tpoisot** [comment]
Not really, just finishing some docstrings and such. I'll probably add a small example with a SDM, and then a few quality of life things. Should be released over the weekend.
