### ISSUE TITLE
JOSS: Community guidelines

### ISSUE THREAD

**Issue by marcjwilliams1** [EcoJulia/SimpleSDMLayers.jl#42]
I don't see any reference to community guidelines for people wishing to contribute. This is the text in the reviewer checklist for reference:

```
Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
```

**Comment by tpoisot** [comment]
We have added the COC and CONTRIBUTING files, as well as ported issues templates (feature request, todo, bug report) and pull request templates from other EcoJulia projects.

This was done in 3a9d1716d868e30827b6d506561e9bf7be7ac736 - we have closed the issue -- @marcjwilliams1, if you have further requested changes, please do mention it here/re-open the issue.
