### ISSUE TITLE
Convert layers+occurrence to features/labels

### ISSUE THREAD

**Issue by gottacatchenall** [EcoJulia/SimpleSDMLayers.jl#59]
Hi folks, I had a few feature ideas that have come up when using the package, happy to help implement any/all of them if they seem good.

A feature I needed was to convert a set of layers and GBIF occupancy points to a set of features (a matrix of environmental variables at each point in the layer) with corresponding labels (0 for points in the layer without occurrence, 1 at each point with occurrence).

It seems like this feature could have widespread utility for using this with `Turing` (as I did) or `Flux`.

My (crude) example code below --- apologies if this already exists in some form

```

function features(environment, occurrence) 

    xDim, yDim = size(environment[1])
    numberSpatialPoints = xDim*yDim
    numFeatures = length(environment)
        
    featuresMatrix = zeros(numberSpatialPoints, numFeatures)
    labels = [false for i in 1:numberSpatialPoints]
    occupancyLayer = getOccupancyLayer(environment[1], occurrence)
    
    cursor = 1
    for pt in 1:numberSpatialPoints
        if (!isnothing(environment[1][pt] ))
            for f in 1:numFeatures
                featuresMatrix[cursor, f] = environment[f][pt]  
                labels[cursor] = occupancyLayer[pt]
            end
            cursor += 1
        end
    end

    return (featuresMatrix[1:cursor, :], labels[1:cursor])
end

```

**Comment by tpoisot** [comment]
Not 100% sure I get what you're trying to do -- is this something similar to the DataFrames interface @gabrieldansereau added?

**Comment by gottacatchenall** [comment]
Pretty similar yes, 

it takes a vector of predictor layers and occurrence data, the types on my function above should be

```
function buildFeaturesMatrix(environment::LT, occurrence::OT) where {LT <: AbstractVector{T} where T <: SimpleSDMPredictor, OT <: GBIFRecords}
   ....
end
```

and returns a matrix `features` with `n` rows and `m` columns where each row corresponds to a non-nothing point in the layer and contains the `m` values from `environment` at that point (one from each `environment` layer). it also returns a vector `labels` of length `n`, which corresponds to if an occurrence record exists at that point in the layer.

**Comment by gottacatchenall** [comment]
The original reason I started thinking about this is for the open standards ecojulia paper we're working on, I thought we could use GBIF.jl/SimpleSDMLayers.jl as an example near the end to highlight julia's syntax/idiomatic style code can integrate 
data from mulitple sources. The idea would be to build an SDM from GBIF/WorldClim in ~10 lines of code and to
show the resulting figure. 

When I started to write it I realized it would be [nowhere near that length](https://github.com/gottacatchenall/ms_data_schema_macroecology/blob/master/src/sdm_example.jl), but a lot of the lines are boilerplate things that seem common enough to all use cases (i.e. #60 #62 )

Is there a plan for `SimpleSDMModels` or something similar? I think wrapping a lot of commonly used models (bioclim, mv logit as I tried in my example, random forests, maxent if we dare) in types could prove useful and enable shorter examples, would be happy to help write some of it

**Comment by tpoisot** [comment]
I have a lot of thoughts on that, hold on until I can formalize them - this afternoon or this evening. Meanwhile, do you think this can end up written as an example like #61 ?

**Comment by gottacatchenall** [comment]
yeah i think so, might need to make a few changes to the code but i'll save it for the pr

**Comment by gottacatchenall** [comment]
looks like i need to be added to the repo though

**Comment by tpoisot** [comment]
Just sent you the invite.

A couple points.

There will absolutely be a `SpeciesDistributionModels.jl` in the future. Won't be called `Simple...`, because the simple in this repo refers to "ease of use" more than "bare bone features". Before we do this, there are a number of things that need to happen.

The first is moving the data sources way from this package, and release a _breaking_ update drawing on `RasterDataSources.jl`, which has a lot more features for getting rasters.

The second thing that needs to happen is a series of convenience functions like the one you describe here. This is not going to be much work at all, but I want to maintain the layer manipulation and actual modelling separate, just like we keep the data download and layer modelling separate.

One thing that *may* have to happen is the addition of a `SimpleSDMLayerStack` type, which might help with just what you describe. But this is not, for the moment, required.

Comments on the actual substance of the issue in the next comment.

**Comment by tpoisot** [comment]
What you describe is essentially doable already:

~~~julia
features = hcat([predictor[occ] for occ in gbif_occurrences]...)
~~~

I haven't tried, and it's obviously not good in terms of memory allocation, but it's there. The think I agree we need is to generate a way to get an occurrence layer from a series of GBIF records, which is easy enough. We can also do a buffer around the observations using `slidingwindow` (which needs to be improved performance wise).

I'm going to add a second example under the SDM section of the doc, called "data preparation", together with a method to make a layer of occurrences. Then we can see if this facilitates your own SDM example (I think it will). On my list of things to do for tonight, I need to fix a few bugs with `rescale` methods first.

**Comment by gottacatchenall** [comment]
ah, i was attempting to get features/labels for all locations in the lattice, not just occupancy locations. i think that's required to do logit, otherwise it would learn to always pick `1` because there aren't data points without occurrence? not sure though

**Comment by tpoisot** [comment]
OK, so with the new functions in #65, this is going to be (I think, not tested yet but we'll make it an example!)

~~~julia
temperature = clip(worldclim(1), records)
sp_layer = mask(temperature, records)
labels = collect(sp_layer)
features = collect(temperature)
~~~

Does this seem OK?

**Comment by tpoisot** [comment]
P.S. I added https://github.com/EcoJulia/SimpleSDMLayers.jl/discussions to have discussions of a more general nature, like "Should we do MaxEnt?" ;-)

**Comment by gottacatchenall** [comment]
sounds great, i'll shift stuff there

**Comment by tpoisot** [comment]
Let's close this one, I'm sure we'll address the "feature extraction" in the example in #64
