### ISSUE TITLE
Recipe for histogram2d?

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SimpleSDMLayers.jl#6]
Question for @mkborregaard 

I've added a recipe for a scatterplot (`scatter(l1, l2)` plots the values of the cells in two layers, and for large maps it would be better to have this as 2d histogram -- is this doable through recipes?

**Comment by mkborregaard** [comment]
sure, with `seriestype := :histogram2d` - do you have a worked example I can expand?
