### ISSUE TITLE
Interfaces for lat and long of ::GBIFRecord

### ISSUE THREAD

**Issue by gottacatchenall** [EcoJulia/SimpleSDMLayers.jl#62]
continuing on #59 

`
latitude(r::GBIFRecord) = r.latitude
longitude(r::GBIFRecord) = r.longitude
`
 as an interface was nice, allthough `latitudes`/`longitudes` are defined already for layers

**Comment by tpoisot** [comment]
So I'm going to keep it plural to avoid growing the namespace, but this does make sense
