### ISSUE TITLE
x and y not respected for heatmap

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/SimpleSDMLayers.jl#7]
According to my (limited) understanding of the recipes system, calling `heatmap` should set the correct values for x and y, through the following lines:

https://github.com/EcoJulia/SimpleSDMLayers.jl/blob/6b2bdf6676f8588e4b5196e13d9c83014bcbaf24/src/recipes/recipes.jl#L5-L7

And yet, when calling it with a layer, as in 

https://github.com/EcoJulia/SimpleSDMLayers.jl/blob/6b2bdf6676f8588e4b5196e13d9c83014bcbaf24/test/plots.jl#L15

I get a figure with the correct z, but the wrong x and y (basically the positions):

![](https://raw.githubusercontent.com/EcoJulia/SimpleSDMLayers.jl/master/test/gallery/heatmap_scaledown.png)

So clearly, there's a step I'm missing -- @mkborregaard do you know the right incantation to get this to work?

**Comment by mkborregaard** [comment]
Yes that should work :thinking_face: I'll have a look when I can. I'm at a science retreat this week but might get some time on Friday on the plane

**Comment by mkborregaard** [comment]
awesome @tpoisot that was actually the solution I wanted to suggest
