### ISSUE TITLE
Extend mask function for DataFrames

### ISSUE THREAD

**Issue by gabrieldansereau** [EcoJulia/SimpleSDMLayers.jl#74]
Love the new `mask` function @tpoisot ! It will be incredibly useful.

I think it would be nice if it worked on `DataFrames` too, not just on `GBIFrecords` elements. That would be in line with the previous `DataFrames` integration I've added, where I mostly mimicked the features from the `GBIF` integration so that both can be used in a similar way.

I created [this function](https://github.com/gabrieldansereau/betadiversity-hotspots/blob/main/src/lib/presence-absence.jl) for my project a while ago and I think it works well enough. I'll update it to be similar to `mask` and add it in a PR, if you agree.

**Comment by gabrieldansereau** [comment]
Also, would you mind if I added an optional `removezeros` argument to `mask` which converts zeros to `nothing`? The default would be `false` to keep the behaviour as it is. I think makes sense since GBIF doesn't return true absences. It's essentially just `replace!(layer, 0 => nothing)`. I'd be doing that all the time if it wasn't included :wink:

I also like how it allows to plot the layer with occupied sites with a background that is not on the colour scale, as on my [richness figures](https://github.com/gabrieldansereau/betadiversity-hotspots/blob/main/fig/raw/04-2_raw_richness.png). It enhances the difference between sites with few occurrences and no occurrences at all. Something like this:
```julia
plot(backgroundlayer, c = :lightgrey)
plot!(occurrencelayer, c = :viridis)
```

**Comment by tpoisot** [comment]
It all makes sense to me, go ahead!

**Comment by tpoisot** [comment]
BUT make sure it works with all types. Most of the bugs I've fixed recently where because we assumed the data would be floating point, and it's not always true.  Maybe a mask function for dataframes, and then the documentation mentions `replace!`?

**Comment by gabrieldansereau** [comment]
Good point, I'll see about it.

I think `replace!(layer, 0 => nothing)` works whether the zero is a `Float`, an `Int`, or a `Bool`. That seems like all the cases where it would potentially make sense to call that argument. Do you see any other ones?

**Comment by tpoisot** [comment]
I think I would like it better to have replace! outside - that's one fewer argument in the function, and it makes people think about whether they really want to remove the 0.

**Comment by tpoisot** [comment]
As soon as #75 is merged (in a minute...), I'll tag a new release with a `replace` and `replace!` method, you can use this to build your thing directly with the layers (instead of the DF).
