### ISSUE TITLE
Changes to DataFrames/GBIF integrations not picked up by Revise.jl

### ISSUE THREAD

**Issue by gabrieldansereau** [EcoJulia/SimpleSDMLayers.jl#77]
I'm trying to use Revise.jl to make the changes discussed in #74, and I'm running into some issues. I'm new to Revise though.

For now, calling `using Revise` before `using SimpleSDMLayers` in a dev project works great when I make changes to any functions from the package, except for the GBIF/DataFrames integrations. I know they are loaded through Requires.jl, but this is supposed to be supported by Revise (see [here](https://discourse.julialang.org/t/revise-with-requires/19347))

I managed to make it work by removing the `joinpath()` in https://github.com/EcoJulia/SimpleSDMLayers.jl/blob/db148a57a597dbb7412bae50b2c0168815ad0df1/src/SimpleSDMLayers.jl#L55-L65 to 

```julia
function __init__()
    @require GBIF="ee291a33-5a6c-5552-a3c8-0f29a1181037" begin
        @info "GBIF integration loaded"
        include("integrations/GBIF.jl")
    end
    @require DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0" begin
        @info "DataFrames integration loaded"
        include("integrations/DataFrames.jl")
    end

end
```

@tpoisot I know your preference for `joinpath`, but do you mind leaving that one? Is there another fix?

**Comment by tpoisot** [comment]
I have never used Revise, so I have no idea why that might be... 

That being said, `joinpath` is actually important here because of the `dirname` / `pathof` part. I would open an issue on Revise.
